# Site settings
title: mastertork
description: Tinker1ng with electr0nics and c0de
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brian Torkelson
user_description: I typically end up spending my free time tinkering with electronics and attempting to write code.  Mostly learning as I go, but every once and a while I get something right.  The majority of my work invloves small development boards like the Raspberry Pi or the ESP8266.  I have been learning more and more about the linux command line, apt-get is life.  I have a strong interest in network security and information security.
user_title: mastertork
email: mastertork.tech@gmail.com
twitter_username: mastertork
github_username: mastertork
youtube_channel: UCNJvX9ZipX-ZkHa6ZOm1efQ

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
