# Site settings
title: mastertork
description: Tinker1ng with electr0nics and c0de
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mastertork
user_description: Spending my free time tinkering with electronics and attempting to write code.  Mostly learning as I go, but every once and a while I get something right.
user_title: Brian Torkelson
email: mastertork.tech@gmail.com
#twitter_username: lorem_ipsum
github_username:  mastertork
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
